### ISSUE TITLE
nodeではなくGoで開発するか？

### ISSUE THREAD

**Issue by akai-inu** [angola-rabbit/angola#10]
# node vs Golang

- nodeの方が採用実績＋情報量共に多い
- Golangの伸びが異常にすごい(特にソケット通信周り)
- 今後の展開を考えるとGolangを今学んだ方が良い
- Golangはコンパイル通すのでハイパフォーマンス

# 参考資料

- http://www.hostingadvice.com/blog/nodejs-vs-golang/
- https://www.cyberagent.co.jp/specialsite/golang/detail/id=10980

**Comment by ike-jp** [comment]
nodeでakai-inuさんが作ったのをGoに移植すると両方の勉強になりそう

**Comment by il-m-yamagishi** [comment]
@ike-jp たのんます

**Comment by vjsigsig** [comment]
軽くPHPで作ってGolangでリファクタリングするという手も？（動いてるしいいか！　ってなりそう）

**Comment by il-m-yamagishi** [comment]
@vjsigsig PHPで書くとこほとんどないんスよねー

**Comment by il-m-yamagishi** [comment]
#11 で移植しますよ〜
